apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "estudiantes.labels" . | nindent 4 }}
type: Opaque
data:
  contacts_mongo_url: {{ .Values.contactsMongoUrl | b64enc }}